// AUTH ACTIONS
export const TRY_LOGIN = "TRY_LOGIN";
export const SAVE_AUTH_TOKENS = "SAVE_AUTH_TOKENS";
export const UPDATE_PROFILE_INFO = "UPDATE_USER_PROFILE";
/* export const REGISTER = "REGISTER";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const RESET_PWD =  "RESET_PASSWORD";
export const LOGOUT = "LOGOUT";

// BOOKING ACTIONS 
export const SET_ORIGIN = "SET_ORIGIN";
export const SET_DESTINATION = "SET_DESTINATION";
export const SET_DATETIME = "SET_RIDE_DATETIME";
export const SET_OCUPANCY = "SET_RIDE_OCUPANCY";
export const DO_BOOKING_REQUEST = "DO_BOOKING_REQUEST";
export const BOOK_RIDE = "BOOK_RIDE";

// MY RIDE MANAGMENT
export const CANCEL_RIDE = "CANCEL_RIDE";
export const CHANGE_RIDE = "CHANGE_RIDE";
export const REFRESH_RIDES = "REFRESH_RIDES";

// PROFILE ACTIONS

export const UPDATE_NOTIFICATION_SETTINGS = "UPDATE_NOTIFICATION_SETTINGS";
export const SET_FAVOURITE_ADDRESS = "SET_FAVOURITE_ADDRESS";

// CONFIGURATIONS
export const CONFIG_BOOKING = "CONFIG_BOOKING";

// DEV ACTIONS 
export const CHANGE_API = "CHANGE_API";
*/


